# Generated by Django 5.2.9 on 2026-01-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('person', models.CharField(max_length=100)),
                ('cau_chuc', models.CharField(max_length=100)),
                ('loai_thiep', models.CharField(max_length=100)),
            ],
        ),
    ]
