# Generated by Django 5.2.9 on 2026-01-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thiep', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='info',
            table='info',
        ),
    ]
