# Generated by Django 5.2.9 on 2026-01-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiep', '0002_alter_info_options_alter_info_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='cau_chuc',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='loai_thiep',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='info',
            name='person',
            field=models.TextField(max_length=50),
        ),
    ]
