# Generated by Django 5.2.9 on 2026-01-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thiep', '0003_alter_info_cau_chuc_alter_info_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='person',
            new_name='person_name',
        ),
    ]
