# Generated by Django 5.2.9 on 2026-01-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('devices', models.TextField()),
            ],
            options={
                'db_table': 'log',
                'managed': True,
            },
        ),
    ]
