# Generated by Django 5.2.9 on 2026-01-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chuc_random', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
