# Generated by Django 5.2.9 on 2026-01-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chuc_random', '0002_alter_log_date_alter_log_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='devices',
            new_name='who',
        ),
        migrations.AddField(
            model_name='log',
            name='loi_chuc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
