# Generated by Django 5.2.9 on 2026-01-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chuc_random', '0003_rename_devices_log_who_log_loi_chuc_alter_log_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.TextField(),
        ),
    ]
