# Generated by Django 5.2.9 on 2026-01-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chuc_random', '0004_alter_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='loai',
            field=models.TextField(blank=True, null=True),
        ),
    ]
